import { useState } from "react";
import { PeptideDeepDive } from "@/components/protocol/PeptideDeepDive";
import { getAllPeptideNames } from "@/lib/peptideDeepDive";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { DashboardLayout } from "@/components/dashboard/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { 
  MessageCircle, 
  ArrowRight, 
  Play, 
  Pause, 
  ChevronDown, 
  ChevronUp,
  AlertTriangle,
  Calendar,
  Printer,
  Download
} from "lucide-react";
import { useProtocol, Protocol } from "@/hooks/useProtocol";
import { useQuizResponse } from "@/hooks/useQuizResponse";
import { getGoalLabel, getPeptideMatch } from "@/lib/quizPersonalization";
import { format } from "date-fns";
import { cn } from "@/lib/utils";

const statusConfig: Record<string, { label: string; color: string; bgColor: string }> = {
  not_started: { label: "Not Started", color: "#6B7280", bgColor: "#F3F4F6" },
  active: { label: "Active", color: "#10B981", bgColor: "rgba(16,185,129,0.1)" },
  paused: { label: "Paused", color: "#F59E0B", bgColor: "rgba(245,158,11,0.1)" },
  completed: { label: "Completed", color: "#10B981", bgColor: "rgba(16,185,129,0.1)" },
};

// Generate printable HTML
function generateProtocolHTML(protocol: Protocol): string {
  const peptidesList = protocol.peptides.map(p => `
    <div style="margin-bottom: 16px; padding: 16px; background: #f8f9fa; border-radius: 8px;">
      <h4 style="margin: 0 0 8px 0; color: #1a1a1a;">${p.name}</h4>
      <p style="margin: 0 0 8px 0; color: #666;">${p.purpose}</p>
      ${p.rationale ? `<p style="margin: 0 0 8px 0; padding: 8px; background: #FFF7ED; border-radius: 4px; font-size: 14px;"><strong>Why this peptide:</strong> ${p.rationale}</p>` : ''}
      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 8px; font-size: 14px;">
        <div><strong>Dosage:</strong> ${p.dosage}</div>
        <div><strong>Frequency:</strong> ${p.frequency}</div>
        <div><strong>Timing:</strong> ${p.timing}</div>
        ${p.site ? `<div><strong>Site:</strong> ${p.site}</div>` : ''}
      </div>
    </div>
  `).join('');

  return `<!DOCTYPE html><html><head><title>${protocol.protocol_name}</title>
    <style>body{font-family:system-ui,sans-serif;max-width:800px;margin:0 auto;padding:40px 20px;color:#1a1a1a}h1{color:#111827}h2{color:#374151;border-bottom:2px solid #e5e7eb;padding-bottom:8px;margin-top:32px}.meta{color:#6b7280;margin-bottom:24px}.disclaimer{background:#FFFBEB;padding:16px;border-radius:8px;font-size:14px;margin-top:32px;border-left:4px solid #F59E0B}@media print{body{padding:20px}}</style>
    </head><body><h1>${protocol.protocol_name}</h1>
    <div class="meta"><p><strong>Goal:</strong> ${protocol.goal}</p><p><strong>Duration:</strong> ${protocol.cycle_length_weeks} weeks</p></div>
    ${protocol.notes ? `<div style="background:#FFF7ED;padding:16px;border-radius:8px;margin-bottom:24px"><strong>Why This Protocol:</strong> ${protocol.notes}</div>` : ''}
    <h2>Peptides</h2>${peptidesList}
    <div class="disclaimer"><strong>Disclaimer:</strong> This protocol is for educational purposes only. Consult a healthcare provider before using any peptides.</div>
    <p style="color:#9ca3af;font-size:12px;margin-top:24px;text-align:center">Generated by Peptide Playbook · ${new Date().toLocaleDateString()}</p></body></html>`;
}

function generateProtocolText(protocol: Protocol): string {
  const lines = [
    `${protocol.protocol_name.toUpperCase()}`,
    `Goal: ${protocol.goal}`,
    `Duration: ${protocol.cycle_length_weeks} weeks`,
    '',
  ];
  if (protocol.notes) lines.push(`Why This Protocol: ${protocol.notes}`, '');
  protocol.peptides.forEach((p, i) => {
    lines.push(`${i + 1}. ${p.name}`, `   Purpose: ${p.purpose}`, `   Dosage: ${p.dosage}`, `   Frequency: ${p.frequency}`, `   Timing: ${p.timing}`, '');
  });
  lines.push('DISCLAIMER: For educational purposes only. Consult a healthcare provider.');
  return lines.join('\n');
}

// Protocol card for user-created protocols
function UserProtocolCard({ 
  protocol, onStart, onPause, onResume, onPrint, onExport,
  isStarting, isPausing, isResuming
}: { 
  protocol: Protocol; onStart: (id: string) => void; onPause: (id: string) => void;
  onResume: (id: string) => void; onPrint: (p: Protocol) => void; onExport: (p: Protocol) => void;
  isStarting: boolean; isPausing: boolean; isResuming: boolean;
}) {
  const [isExpanded, setIsExpanded] = useState(false);
  const status = statusConfig[protocol.status] || statusConfig.not_started;
  const createdDate = protocol.created_at ? format(new Date(protocol.created_at), "MMM d, yyyy") : "";

  return (
    <div className="rounded-2xl bg-white overflow-hidden" style={{ boxShadow: "0 1px 3px rgba(0,0,0,0.08)" }}>
      <div className="p-5">
        <div className="flex items-start justify-between gap-3 mb-3">
          <div className="flex-1 min-w-0">
            <h3 className="font-semibold truncate" style={{ color: "#111827" }}>{protocol.protocol_name}</h3>
            <p className="text-sm" style={{ color: "#6B7280" }}>
              {protocol.status === "not_started" 
                ? `${protocol.cycle_length_weeks} week cycle`
                : `Week ${protocol.current_week} of ${protocol.cycle_length_weeks}`}
            </p>
          </div>
          <span className="px-2.5 py-0.5 rounded-full text-xs font-medium shrink-0" style={{ backgroundColor: status.bgColor, color: status.color }}>
            {status.label}
          </span>
        </div>

        <div className="flex flex-wrap gap-1.5 mb-3">
          {protocol.peptides.slice(0, 3).map((p, idx) => (
            <span key={idx} className="px-2 py-0.5 text-xs rounded-full" style={{ backgroundColor: "#F3F4F6", color: "#6B7280" }}>{p.name}</span>
          ))}
        </div>

        <div className="flex items-center gap-3 text-xs mb-4" style={{ color: "#9CA3AF" }}>
          <span className="flex items-center gap-1"><Calendar className="w-3 h-3" /> Created {createdDate}</span>
        </div>

        <div className="flex items-center gap-2">
          {protocol.status === "not_started" && (
            <Button size="sm" onClick={() => onStart(protocol.id)} disabled={isStarting} className="rounded-full" style={{ backgroundColor: "#111827" }}>
              <Play className="w-3.5 h-3.5 mr-1.5" />{isStarting ? "Starting..." : "Start"}
            </Button>
          )}
          {protocol.status === "active" && (
            <Button size="sm" variant="outline" onClick={() => onPause(protocol.id)} disabled={isPausing} className="rounded-full">
              <Pause className="w-3.5 h-3.5 mr-1.5" />{isPausing ? "Pausing..." : "Pause"}
            </Button>
          )}
          {protocol.status === "paused" && (
            <Button size="sm" onClick={() => onResume(protocol.id)} disabled={isResuming} className="rounded-full" style={{ backgroundColor: "#111827" }}>
              <Play className="w-3.5 h-3.5 mr-1.5" />{isResuming ? "Resuming..." : "Resume"}
            </Button>
          )}
          <Button size="sm" variant="ghost" onClick={() => setIsExpanded(!isExpanded)} className="rounded-full">
            View {isExpanded ? <ChevronUp className="w-3.5 h-3.5 ml-1" /> : <ChevronDown className="w-3.5 h-3.5 ml-1" />}
          </Button>
          <Button size="sm" variant="ghost" onClick={() => onPrint(protocol)} className="rounded-full">
            <Printer className="w-3.5 h-3.5" />
          </Button>
          <Button size="sm" variant="ghost" onClick={() => onExport(protocol)} className="rounded-full">
            <Download className="w-3.5 h-3.5" />
          </Button>
        </div>

        {isExpanded && (
          <div className="pt-4 mt-4 space-y-3" style={{ borderTop: "1px solid #E5E7EB" }}>
            {protocol.notes && (
              <div className="p-3 rounded-xl" style={{ backgroundColor: "#FFF7ED" }}>
                <h4 className="text-sm font-medium mb-1 flex items-center gap-1.5" style={{ color: "#111827" }}>
                  <MessageCircle className="w-3.5 h-3.5" style={{ color: "#F97316" }} /> Why This Protocol
                </h4>
                <p className="text-sm" style={{ color: "#6B7280" }}>{protocol.notes}</p>
              </div>
            )}
            {protocol.peptides.map((peptide, index) => (
              <div key={index} className="p-3 rounded-xl" style={{ border: "1px solid #E5E7EB" }}>
                <div className="flex items-center justify-between mb-2">
                  <h4 className="font-medium" style={{ color: "#111827" }}>{peptide.name}</h4>
                  <span className="text-xs px-2 py-0.5 rounded-full" style={{ backgroundColor: "#F3F4F6", color: "#6B7280" }}>{peptide.frequency}</span>
                </div>
                <p className="text-sm mb-2" style={{ color: "#6B7280" }}>{peptide.purpose}</p>
                {peptide.rationale && (
                  <p className="text-xs p-2 rounded-lg mb-2" style={{ backgroundColor: "#FFF7ED", color: "#374151" }}>
                    <span className="font-medium" style={{ color: "#F97316" }}>Why:</span> {peptide.rationale}
                  </p>
                )}
                <div className="grid grid-cols-2 gap-2 text-xs">
                  <div><span style={{ color: "#9CA3AF" }}>Dosage:</span> <span style={{ color: "#374151" }}>{peptide.dosage}</span></div>
                  <div><span style={{ color: "#9CA3AF" }}>Timing:</span> <span style={{ color: "#374151" }}>{peptide.timing}</span></div>
                </div>
              </div>
            ))}
            <div className="p-3 rounded-xl" style={{ backgroundColor: "#FFFBEB", borderLeft: "4px solid #F59E0B" }}>
              <p className="text-xs" style={{ color: "#92400E" }}>
                <AlertTriangle className="w-3.5 h-3.5 inline mr-1" />
                This protocol is for educational purposes only. Consult a healthcare provider before using any peptides.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

const containerVariants = {
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren: 0.1 } },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0 },
};

export default function Protocols() {
  const [mutatingId, setMutatingId] = useState<string | null>(null);
  const [mutationType, setMutationType] = useState<"start" | "pause" | "resume" | null>(null);

  const { protocols, isLoadingProtocols, startProtocol, pauseProtocol, resumeProtocol } = useProtocol();
  const { data: quizResponse } = useQuizResponse();

  const goalLabel = quizResponse ? getGoalLabel(quizResponse.primary_goal) : null;
  const peptideMatch = quizResponse ? getPeptideMatch(quizResponse.primary_goal) : null;

  // All available peptides from the deep dive library
  const allPeptideNames = getAllPeptideNames();
  
  // Matched peptide names
  const matchedNames = peptideMatch ? [peptideMatch.primary, peptideMatch.secondary] : [];
  const otherNames = allPeptideNames.filter(name => !matchedNames.includes(name));

  const handleStart = async (id: string) => {
    setMutatingId(id); setMutationType("start");
    try { await startProtocol.mutateAsync(id); } finally { setMutatingId(null); setMutationType(null); }
  };
  const handlePause = async (id: string) => {
    setMutatingId(id); setMutationType("pause");
    try { await pauseProtocol.mutateAsync(id); } finally { setMutatingId(null); setMutationType(null); }
  };
  const handleResume = async (id: string) => {
    setMutatingId(id); setMutationType("resume");
    try { await resumeProtocol.mutateAsync(id); } finally { setMutatingId(null); setMutationType(null); }
  };

  const handlePrint = (protocol: Protocol) => {
    const printContent = generateProtocolHTML(protocol);
    const printWindow = window.open('', '_blank');
    if (printWindow) { printWindow.document.write(printContent); printWindow.document.close(); printWindow.print(); }
  };

  const handleExport = (protocol: Protocol) => {
    const content = generateProtocolText(protocol);
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `${protocol.protocol_name.replace(/\s+/g, '-')}-protocol.txt`; a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <DashboardLayout>
      <motion.div 
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="space-y-8 py-4 md:py-8"
      >
        {/* Header */}
        <motion.div variants={itemVariants}>
          <h1 className="text-[28px] font-bold" style={{ color: "#111827" }}>Your Peptide Protocols</h1>
          <p className="text-[15px]" style={{ color: "#6B7280" }}>Research-backed protocols matched to your goals</p>
        </motion.div>

        {/* User-created protocols (if any) */}
        {protocols && protocols.length > 0 && (
          <motion.div variants={itemVariants} className="space-y-4">
            <h2 className="text-sm font-semibold uppercase tracking-wider" style={{ color: "#6B7280" }}>
              Your Custom Protocols
            </h2>
            {protocols.map((protocol) => (
              <UserProtocolCard
                key={protocol.id}
                protocol={protocol}
                onStart={handleStart}
                onPause={handlePause}
                onResume={handleResume}
                onPrint={handlePrint}
                onExport={handleExport}
                isStarting={mutatingId === protocol.id && mutationType === "start"}
                isPausing={mutatingId === protocol.id && mutationType === "pause"}
                isResuming={mutatingId === protocol.id && mutationType === "resume"}
              />
            ))}
          </motion.div>
        )}

        {/* Chat CTA */}
        <motion.div variants={itemVariants}>
          <div className="rounded-2xl p-6 bg-white" style={{ boxShadow: "0 1px 3px rgba(0,0,0,0.08)", border: "2px dashed #E5E7EB" }}>
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl flex items-center justify-center shrink-0" style={{ backgroundColor: "rgba(249,115,22,0.1)" }}>
                <MessageCircle className="w-6 h-6" style={{ color: "#F97316" }} />
              </div>
              <div className="flex-1">
                <h2 className="text-lg font-semibold mb-1" style={{ color: "#111827" }}>Build Your Custom Protocol</h2>
                <p className="text-sm mb-4" style={{ color: "#6B7280" }}>
                  Talk to our AI Coach to build a personalized protocol tailored to your goals, health history, and experience level.
                </p>
                <Button asChild className="rounded-full" style={{ backgroundColor: "#111827" }}>
                  <Link to="/dashboard/chat">
                    Talk to AI Coach <ArrowRight className="w-4 h-4 ml-2" />
                  </Link>
                </Button>
              </div>
            </div>
          </div>
        </motion.div>

        {/* Matched Peptides Section */}
        {matchedNames.length > 0 && (
          <motion.div variants={itemVariants} className="space-y-4">
            <h2 className="text-sm font-semibold uppercase tracking-wider" style={{ color: "#6B7280" }}>
              {goalLabel ? `Matched to Your ${goalLabel} Goal` : "Your Matched Peptides"}
            </h2>
            {matchedNames.map((name, index) => (
              <motion.div
                key={name}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
              >
                <PeptideDeepDive
                  peptideName={name}
                  goal={goalLabel?.toLowerCase()}
                  isMatched
                  defaultOpen={index === 0}
                />
              </motion.div>
            ))}
          </motion.div>
        )}

        {/* Other Peptides */}
        <motion.div variants={itemVariants} className="space-y-4">
          <div className="pt-4" style={{ borderTop: "1px solid #E5E7EB" }}>
            <h2 className="text-[20px] font-bold mb-1" style={{ color: "#111827" }}>Explore Other Peptides</h2>
            <p className="text-sm mb-4" style={{ color: "#6B7280" }}>Full research profiles for all peptides in our database</p>
          </div>
          {otherNames.map((name, index) => (
            <motion.div
              key={name}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 + index * 0.1 }}
            >
              <PeptideDeepDive peptideName={name} goal={goalLabel?.toLowerCase()} />
            </motion.div>
          ))}
        </motion.div>

        {/* Loading state */}
        {isLoadingProtocols && (
          <div className="space-y-4">
            {[1, 2].map((i) => (
              <Skeleton key={i} className="h-32 w-full rounded-2xl" />
            ))}
          </div>
        )}

        {/* Disclaimer footer */}
        <motion.div
          variants={itemVariants}
          className="text-xs text-center py-6"
          style={{ color: "#9CA3AF", borderTop: "1px solid #E5E7EB" }}
        >
          <p>For educational purposes only. Not medical advice. Always consult a healthcare provider before using any peptides.</p>
        </motion.div>
      </motion.div>
    </DashboardLayout>
  );
}
