-- Seed Recovery Course Template with full 42-day lesson content
-- Higher doses for acute injury recovery

UPDATE course_templates
SET 
  duration_days = 42,
  peptides = '[
    {
      "name": "BPC-157",
      "purpose": "Accelerated injury healing",
      "dosing_research": "500mcg twice daily (Weeks 1-3), then 250mcg twice daily (Weeks 4-6)",
      "timing": "Morning and evening, near injury site",
      "frequency": "Twice daily",
      "site": "Within 2-3 inches of injury",
      "notes": "Higher initial dose for aggressive healing, then taper"
    },
    {
      "name": "TB-500",
      "purpose": "Systemic healing and inflammation reduction",
      "dosing_research": "5mg twice weekly (Weeks 1-3), then 2.5mg once weekly (Weeks 4-6)",
      "timing": "Any time, consistent days (e.g., Monday/Thursday)",
      "frequency": "Twice weekly loading, then once weekly",
      "site": "Subcutaneous, abdomen or thigh",
      "notes": "Aggressive loading phase for faster recovery"
    }
  ]'::jsonb,
  lessons = '[
    {"day": 0, "phase": "Aggressive Healing", "title": "Welcome to Your Injury Recovery Course", "content": "Welcome to the Injury Recovery Course. This is an intensive 6-week protocol designed specifically for healing injuries, strains, and chronic pain. Unlike our muscle course, we are using higher doses upfront to accelerate your healing.\n\nYour protocol uses the same powerful peptides—BPC-157 and TB-500—but at aggressive loading doses. BPC-157 starts at 500mcg twice daily (double the standard dose), and TB-500 at 5mg twice weekly (also doubled). This front-loads healing factors to give your body maximum support when it needs it most.\n\nAfter 3 weeks, we taper to maintenance doses as your injury heals. This approach is backed by research showing that higher initial doses accelerate tissue repair.\n\nThe key difference: Every BPC-157 injection should be as close to your injury as safely possible. This targets the healing factors exactly where they are needed.", "action_item": "Locate your injury site and identify the closest safe injection point (2-3 inches from the area)."},
    {"day": 1, "phase": "Aggressive Healing", "title": "BPC-157 for Injury Recovery", "content": "BPC-157 is particularly powerful for injury recovery. This peptide, derived from human gastric juice, has been studied extensively for tissue repair.\n\nFor injuries specifically, BPC-157 works by: promoting angiogenesis (new blood vessel formation) at the injury site, accelerating tendon and ligament healing, reducing local inflammation, and supporting muscle tissue repair.\n\nThe reason we use higher doses (500mcg vs standard 250mcg) for injury recovery is that research suggests dose-dependent effects on healing speed. More peptide at the injury site means more healing factors available.\n\nInjecting near the injury delivers BPC-157 directly where it is needed. While systemic (abdominal) injections also work, targeted injections near the injury site show faster local healing in anecdotal reports.", "action_item": "Review the BPC-157 information in your My Plan tab and understand why we are using higher doses."},
    {"day": 2, "phase": "Aggressive Healing", "title": "TB-500 for Systemic Healing", "content": "TB-500 (Thymosin Beta-4) complements BPC-157 perfectly for injury recovery. While BPC-157 targets local healing, TB-500 works systemically throughout your body.\n\nTB-500 works by upregulating actin (a cell-building protein), promoting cell migration to injury sites, reducing inflammation throughout the body, and supporting flexibility and mobility.\n\nFor injury recovery, we start with an aggressive 5mg twice weekly loading phase. This is higher than our muscle protocol because we want maximum systemic healing support during the critical early weeks of recovery.\n\nYou may experience temporary lethargy during the loading phase—this is normal and indicates the peptide is working. Your body is redirecting energy toward healing.", "action_item": "Mark your TB-500 injection days on your calendar (e.g., Monday and Thursday for consistency)."},
    {"day": 3, "phase": "Aggressive Healing", "title": "Reconstitution for Higher Doses", "content": "Today we reconstitute your peptides. Because you are using higher doses, your reconstitution strategy is slightly different.\n\nFor BPC-157 (5mg vial): Add 2ml bacteriostatic water. This gives you 2.5mg per ml, or 250mcg per 10 units. For your 500mcg doses, you will draw 20 units per injection. At 2 injections daily, one vial lasts about 5 days.\n\nFor TB-500 (5mg vial): Add 1ml bacteriostatic water. This gives you 5mg per ml—your entire dose in one draw. Each vial equals one injection.\n\nImportant: You will go through supplies faster than muscle course users. Make sure you have enough vials ordered for the full 6 weeks. You will need approximately 6 BPC-157 vials and 6 TB-500 vials for the loading phase.", "action_item": "Reconstitute your first BPC-157 vial and first TB-500 vial. Store in refrigerator."},
    {"day": 4, "phase": "Aggressive Healing", "title": "Your First Injections", "content": "Today you begin your injury recovery protocol. You will be doing 3 injections today: BPC-157 morning (near injury), BPC-157 evening (near injury), and TB-500 (anywhere subcutaneous).\n\nFor BPC-157 near your injury: Identify a point 2-3 inches from the injury site. Clean with alcohol swab. Pinch skin, insert needle at 45 degrees, inject slowly, withdraw. For TB-500: Choose abdomen or thigh. Same technique.\n\nWhat to expect: The injections should be nearly painless. You might feel slight warmth or tingling near the injury site—this is normal and some people report it as a positive sign. TB-500 can cause a brief head rush immediately after injection; this passes in seconds.", "action_item": "Complete all three injections. Note the time and any sensations in your journal."},
    {"day": 5, "phase": "Aggressive Healing", "title": "Injury Site Injection Strategy", "content": "Now that you have done your first injections, let us refine your technique for maximum healing benefit.\n\nThe goal with injury-site injections is to deliver BPC-157 as close to the damaged tissue as possible, while staying safe. For tendon or ligament injuries: inject into the fatty tissue overlying the area, not into the tendon itself. For muscle injuries: inject into the muscle belly near the strain. For joint issues: inject into subcutaneous tissue near the joint capsule.\n\nRotate your exact injection points slightly each time to prevent any single spot from becoming irritated. You might use a mental grid—upper left, upper right, lower left, lower right—around your injury site.", "action_item": "Map out 4 injection points around your injury site for rotation."},
    {"day": 6, "phase": "Aggressive Healing", "title": "The Day After", "content": "How do you feel? It has been 2 days of injections now. Here is what is normal:\n\nAt the injury site: Some people notice reduced pain or swelling already. Others feel no different yet. Both are normal—healing timelines vary by injury type and severity. Systemically: TB-500 can cause mild fatigue. Your body is working hard on repair. Energy levels usually normalize within a week.\n\nWhat is not normal: Significant redness, swelling, or warmth at injection sites (beyond mild irritation). Fever or flu-like symptoms. Increased pain at the injury (some soreness is normal, sharp increase is not).\n\nIf you experience anything concerning, pause and consult a healthcare provider. Safety first.", "action_item": "Rate your injury pain 1-10 compared to before starting. This is your baseline for tracking progress."},
    {"day": 7, "phase": "Aggressive Healing", "title": "Week 1 Complete", "content": "Congratulations on completing your first week of injury recovery protocol. You have done 14 BPC-157 injections and 2 TB-500 injections. That is serious commitment to healing.\n\nLet us assess: Injection comfort level—are you getting more confident? Injury status—any changes in pain, swelling, or mobility? Energy levels—how is the TB-500 affecting you? Routine—have you established consistent morning and evening times?\n\nThis first week was about learning and establishing your routine. The peptides are now building in your system, and your body is receiving consistent healing signals. Weeks 2-3 are where many people start noticing real changes.", "action_item": "Write a brief Week 1 summary: How is the injury? How is the routine? Any concerns?"},
    {"day": 8, "phase": "Aggressive Healing", "title": "Week 2: Maximizing Healing", "content": "Welcome to Week 2. Your body has now received a full week of healing peptides. The loading phase continues—same doses, same frequency. Consistency is key.\n\nThis week, focus on supporting your healing with other factors: Rest the injured area as much as reasonably possible. Prioritize sleep—healing happens during deep sleep. Eat adequate protein (at least 0.8g per pound bodyweight). Stay hydrated. Consider adding collagen peptides (oral) and vitamin C to support tissue repair.\n\nYour injections are providing the signals for healing. But your body needs raw materials and rest to execute that healing.", "action_item": "Audit your sleep and protein intake. Identify one improvement you can make this week."},
    {"day": 9, "phase": "Aggressive Healing", "title": "Understanding Inflammation", "content": "Inflammation is complex when it comes to injury recovery. Some inflammation is necessary—it is part of the healing process. But chronic or excessive inflammation slows healing.\n\nBPC-157 and TB-500 both help modulate inflammation rather than just suppress it. They reduce excessive inflammation while allowing the healthy inflammatory response needed for repair.\n\nThis is different from NSAIDs (ibuprofen, naproxen) which broadly suppress inflammation and can actually slow tissue healing. If possible, minimize NSAID use during your recovery protocol. If you need pain management, discuss alternatives with your healthcare provider.", "action_item": "Review any anti-inflammatory medications you are taking. Consider if they are necessary."},
    {"day": 10, "phase": "Aggressive Healing", "title": "Vial Management", "content": "At your consumption rate, you have likely finished your first BPC-157 vial or are close to it. Time to reconstitute your second.\n\nTracking your supplies is important with the higher-dose protocol. Keep a simple log: Vial reconstituted date, doses remaining, and when you need to order more. You should order your next set of vials before you run out—shipping can take time.\n\nFor a 6-week injury recovery course at loading doses, plan for approximately 8-10 BPC-157 vials and 8 TB-500 vials total. Better to have extras than to run out mid-protocol.", "action_item": "Check your supply levels. Order more vials if you have less than 2 weeks of stock remaining."},
    {"day": 11, "phase": "Aggressive Healing", "title": "Listening to Your Body", "content": "By now you should be developing a relationship with your injury. Pay attention to: Pain patterns—when is it worse, when is it better? Mobility—are you gaining range of motion? Response to activity—how does the injury react to use? Sleep quality—are you sleeping better or worse?\n\nDocument these observations. They help you understand if the protocol is working and can inform decisions about continuing, adjusting, or seeking additional treatment.\n\nNot every day will show improvement. Healing is not linear. Some days will feel like setbacks. Trust the process while staying attentive.", "action_item": "Create a simple daily log: Pain level (1-10), mobility (1-10), and any notes."},
    {"day": 12, "phase": "Aggressive Healing", "title": "Movement and Healing", "content": "The old advice of complete rest for injuries is outdated for most situations. Controlled, gentle movement often accelerates healing by improving blood flow, preventing stiffness, maintaining muscle, and sending healthy stress signals to healing tissue.\n\nThis does not mean pushing through pain. It means gentle movement within comfortable ranges. For a shoulder injury, that might be pendulum swings. For a knee, gentle bending. For a back, cat-cow stretches.\n\nConsult with a physical therapist if possible. They can design a movement protocol that complements your peptide protocol.", "action_item": "Research or ask about gentle movement exercises appropriate for your specific injury."},
    {"day": 13, "phase": "Aggressive Healing", "title": "Week 2 Checkpoint", "content": "Two weeks of consistent peptide therapy complete. Let us assess:\n\nHas pain decreased from your Day 7 baseline? Are you seeing any improvement in mobility or function? How are the injections going—any site irritation? Is the routine sustainable?\n\nMany people notice meaningful improvement by Week 2. If you are not seeing changes yet, do not despair. Some injuries, especially chronic ones, take longer to respond. The peptides are working at the cellular level even before you feel it.", "action_item": "Compare your current pain and mobility to Week 1. Note any changes, positive or negative."},
    {"day": 14, "phase": "Aggressive Healing", "title": "Midpoint of Loading Phase", "content": "You are halfway through the aggressive loading phase. One more week of high doses, then we taper.\n\nAt this point, you have received approximately 14,000mcg (14mg) of BPC-157 and 20mg of TB-500. That is a significant amount of healing peptides. Your body has been receiving constant signals to repair tissue.\n\nThis week, maintain your focus on consistency. Do not skip doses because you are feeling better—the goal is to build maximum healing momentum before tapering.", "action_item": "Recommit to perfect consistency for the final week of loading."},
    {"day": 15, "phase": "Aggressive Healing", "title": "Week 3: Final Loading Week", "content": "This is your last week of aggressive dosing. After Day 21, you will reduce to maintenance doses: BPC-157 drops to 250mcg twice daily, and TB-500 drops to 2.5mg once weekly.\n\nMake this week count. Continue all injections on schedule. Pay attention to how you are feeling so you can compare to maintenance phase. Start planning for the reduced frequency—it will feel strange to inject less after 3 weeks of intensity.", "action_item": "Mark Day 22 on your calendar as the start of maintenance phase."},
    {"day": 16, "phase": "Aggressive Healing", "title": "The Science of Tissue Repair", "content": "Understanding what is happening in your body can help you stay motivated. When tissue is injured, your body goes through phases: Inflammatory phase (days 1-5), Proliferative phase (days 5-21), and Remodeling phase (days 21-2 years).\n\nBPC-157 and TB-500 support all three phases but particularly accelerate the proliferative phase, where new tissue is actually built. This is why we use aggressive dosing early—to maximize support during active tissue construction.\n\nBy Week 3, much of your new tissue is formed. The maintenance phase supports the longer remodeling process.", "action_item": "Identify which phase of healing your injury is likely in."},
    {"day": 17, "phase": "Aggressive Healing", "title": "Nutrition for Healing", "content": "Your body needs building blocks to repair tissue. Key nutrients for healing include: Protein (amino acids for tissue building), Vitamin C (collagen synthesis), Zinc (immune function and wound healing), Vitamin D (immune modulation), and Omega-3s (inflammation management).\n\nConsider adding these to your protocol if you are not already getting adequate amounts. A simple addition: collagen peptides (oral) plus vitamin C in the morning can provide direct building blocks for connective tissue.", "action_item": "Review your diet and supplementation. Add collagen plus vitamin C if appropriate."},
    {"day": 18, "phase": "Aggressive Healing", "title": "Managing Expectations", "content": "Injuries have different healing timelines. Muscle strains may respond in weeks. Tendon injuries often take months. Chronic conditions may need multiple courses. Severe injuries may need additional interventions.\n\nPeptides accelerate healing but cannot perform miracles. If your injury is severe or has been present for years, one 6-week course may not fully resolve it. That is okay—you may run additional courses or combine with other treatments.\n\nThe goal is meaningful improvement, not necessarily complete resolution. Any reduction in pain and improvement in function is a win.", "action_item": "Set realistic expectations for what you hope to achieve by course end."},
    {"day": 19, "phase": "Aggressive Healing", "title": "Sleep and Healing", "content": "Sleep is when your body does most of its repair work. Growth hormone peaks during deep sleep, and this is when tissue regeneration accelerates.\n\nFor optimal healing: Aim for 7-9 hours of sleep. Keep a consistent sleep schedule. Avoid screens before bed. Keep your room cool and dark. Consider magnesium before bed for deeper sleep.\n\nYour peptides are sending healing signals 24/7, but the actual repair work happens primarily while you sleep. Optimize this window.", "action_item": "Rate your sleep quality 1-10. Identify one improvement you can make tonight."},
    {"day": 20, "phase": "Aggressive Healing", "title": "Preparing for Taper", "content": "In 2 days, you will reduce your doses. Here is what to expect:\n\nPhysically: The transition should be smooth. You have built up peptide levels, and the maintenance doses will sustain them. Psychologically: You may worry about reducing doses. Trust the protocol—maintenance dosing is effective for sustained healing. Practically: Fewer injections mean a simpler routine. You will go from 16 weekly injections to 9.\n\nThe maintenance phase is not lesser—it is the appropriate next step in your healing journey.", "action_item": "Mentally prepare for the dose reduction. It is part of the plan."},
    {"day": 21, "phase": "Aggressive Healing", "title": "Loading Phase Complete", "content": "Congratulations! You have completed 3 weeks of aggressive loading. That is 42 BPC-157 injections and 6 TB-500 injections at high doses.\n\nTake stock: How does your injury feel compared to Day 0? What has changed? What still needs work? How was the protocol for you?\n\nStarting tomorrow, you will begin maintenance: BPC-157 250mcg twice daily and TB-500 2.5mg once weekly. This is still an active healing protocol, just at sustainable doses for the next 3 weeks.", "action_item": "Write a summary of your loading phase results. Compare Day 21 to Day 0."},
    {"day": 22, "phase": "Continued Recovery", "title": "Starting Maintenance Phase", "content": "Welcome to maintenance. Your doses are now: BPC-157: 250mcg twice daily (half of loading dose), and TB-500: 2.5mg once weekly (half of loading dose). You will continue these for 3 more weeks.\n\nWhat to expect: Benefits should continue and may even peak. Fewer injections means easier routine. Your body continues healing with sustained support. Many people actually feel better during maintenance because they are less fatigued from the aggressive loading.", "action_item": "Complete your first maintenance-dose injections. Note any difference in how you feel."},
    {"day": 23, "phase": "Continued Recovery", "title": "Adjusting to Reduced Doses", "content": "The first few days of maintenance can feel strange after 3 weeks of intensity. You might wonder if you are doing enough. You are.\n\nThe loading phase built your peptide levels. Maintenance sustains them. Think of it like building a foundation, then maintaining the structure. The heavy construction is done; now you are supporting what was built.\n\nYour healing continues. The cellular processes started during loading do not just stop—they continue with maintenance support.", "action_item": "Trust the maintenance protocol. Stay consistent."},
    {"day": 24, "phase": "Continued Recovery", "title": "Activity Progression", "content": "As your injury improves, you may be able to gradually increase activity. The key word is gradually. Progressive loading means slowly increasing stress on the healing tissue to build strength.\n\nWork with a physical therapist if possible. Otherwise, follow the general principle: start below what you think you can do, and increase by 10-20% per week only if there is no pain increase.\n\nPeptides support tissue repair, but the tissue also needs appropriate stress to reorganize and strengthen properly.", "action_item": "Identify the next small step in activity progression for your injury."},
    {"day": 25, "phase": "Continued Recovery", "title": "Week 4 Checkpoint", "content": "Four weeks into your recovery protocol. Two-thirds done. Let us assess:\n\nPain: What is your level now vs. Day 0? Mobility: What movements are easier? Function: What can you do now that you could not before? Routine: How is maintenance feeling?\n\nMost people see significant improvement by Week 4. If you are not, consider whether the injury may need additional intervention or a longer timeline.", "action_item": "Document your Week 4 status in detail."},
    {"day": 26, "phase": "Continued Recovery", "title": "Chronic vs. Acute Injuries", "content": "If your injury is chronic (present for months or years), your timeline for full healing may be longer than this 6-week course.\n\nChronic injuries often involve: Scar tissue that needs to be remodeled, compensatory patterns that have developed, and deeper tissue changes that take time to reverse.\n\nOne course may provide significant relief. But planning for a second course, after a 4-week break, is often beneficial for chronic conditions. Think of it as multiple phases of rehabilitation.", "action_item": "Assess whether your injury is acute or chronic, and plan accordingly."},
    {"day": 27, "phase": "Continued Recovery", "title": "Supporting Treatments", "content": "Peptides work well alongside other therapies. Consider combining with: Physical therapy (mobility, strength), Massage therapy (blood flow, tissue work), Chiropractic if appropriate, PRP or stem cell therapy for severe injuries, and Acupuncture.\n\nThese treatments can complement your peptide protocol by providing different mechanisms of healing support. Always inform your practitioners that you are using peptides.", "action_item": "Research one complementary therapy that might benefit your recovery."},
    {"day": 28, "phase": "Continued Recovery", "title": "One Month Complete", "content": "You have completed one month of your injury recovery protocol. That is 4 weeks of consistent healing support, 2 weeks remaining.\n\nReflect on: What you have learned about your body, How the injury has responded, What you will do differently in the future (prevention), and Whether you need a second course.\n\nThe final 2 weeks will continue maintenance dosing while you plan your next steps.", "action_item": "Write a one-month reflection on your recovery journey."},
    {"day": 29, "phase": "Continued Recovery", "title": "Week 5: Final Stretch", "content": "Two weeks remaining. Continue your maintenance protocol: BPC-157 twice daily at 250mcg, TB-500 once weekly at 2.5mg.\n\nThis week, start thinking about what comes after Day 42. Options include: Taking a 4-week break and running another course, Continuing BPC-157 at maintenance indefinitely (many do this), Stopping and reassessing your injury status, and Transitioning to occasional or as-needed use.", "action_item": "Begin planning your post-course strategy."},
    {"day": 30, "phase": "Continued Recovery", "title": "Injury Prevention", "content": "As you heal, think about what caused the injury and how to prevent recurrence.\n\nCommon factors include: Training errors (too much, too fast), Poor movement patterns, Inadequate warm-up, Muscle imbalances, Overuse without recovery.\n\nAddressing root causes is as important as healing the injury. Otherwise, you may find yourself back here again.", "action_item": "Identify 2-3 factors that may have contributed to your injury."},
    {"day": 31, "phase": "Continued Recovery", "title": "Long-term Use Considerations", "content": "Many people continue using BPC-157 or TB-500 after their initial healing course. Approaches include: Maintenance use: low dose BPC-157 daily for ongoing support, Cycling: one month on, one month off, and As-needed: when you have a new injury or issue.\n\nThere is no established maximum duration for use. Some people have used BPC-157 for years. Listen to your body and consult with knowledgeable practitioners.", "action_item": "Decide which long-term approach appeals to you."},
    {"day": 32, "phase": "Continued Recovery", "title": "Week 5 Checkpoint", "content": "Five weeks complete. One week remaining. How does your injury feel? Compared to Day 0? Compared to Week 1? What percentage improvement would you estimate?\n\nMost successful courses see 50-80% improvement in pain and function. Complete resolution varies by injury type and severity.", "action_item": "Estimate your percentage improvement from baseline."},
    {"day": 33, "phase": "Continued Recovery", "title": "Documenting Your Results", "content": "Take time to document your complete recovery journey. This is valuable for: Tracking what works for your body, Sharing with practitioners, Planning future courses, and Helping others who may benefit.\n\nInclude: Starting pain and function levels, Timeline of improvements, Any side effects, Protocol details, and Final status.", "action_item": "Write a comprehensive recovery summary."},
    {"day": 34, "phase": "Continued Recovery", "title": "Preparing for Course End", "content": "In one week, your course ends. Make sure you are prepared: Use remaining peptides—do not let them go to waste. Plan your break period (if taking one). Order supplies if running another course. Schedule any follow-up appointments.\n\nThe end of a course is not the end of healing. The tissue repair you have stimulated continues even after you stop the peptides.", "action_item": "Create your post-course plan."},
    {"day": 35, "phase": "Continued Recovery", "title": "Week 5 Complete", "content": "Five of six weeks done. One week of maintenance remaining.\n\nYour injury has had 5 weeks of consistent peptide support. The healing that has occurred is real—new tissue has been built, inflammation has been modulated, and repair processes have been accelerated.\n\nThis final week is about finishing strong and setting yourself up for continued success.", "action_item": "Commit to perfect consistency for the final week."},
    {"day": 36, "phase": "Continued Recovery", "title": "Final Week Begins", "content": "Your last week of the Injury Recovery Course. Continue your maintenance doses: BPC-157 250mcg twice daily, TB-500 2.5mg once (if this is your scheduled day).\n\nThis week, focus on: Completing all remaining doses, Final documentation, Planning next steps, and Celebrating your progress.", "action_item": "Count your remaining doses and plan to use them all."},
    {"day": 37, "phase": "Continued Recovery", "title": "What You Have Achieved", "content": "Take a moment to appreciate what you have done. Over 6 weeks, you have: Completed approximately 84 BPC-157 injections, Completed approximately 9 TB-500 injections, Maintained daily consistency, Supported your body through healing.\n\nThis is significant commitment. Whatever your results, you gave your body the best chance to heal.", "action_item": "List every improvement you have noticed, no matter how small."},
    {"day": 38, "phase": "Continued Recovery", "title": "If You Need More", "content": "If your injury is not fully resolved, do not be discouraged. Some injuries simply need more time or additional courses. Recommended approach: Take a 4-week break, then run another 42-day course. Consider combining with physical therapy or other treatments. Evaluate for underlying issues that may be preventing healing.\n\nHealing is not always linear or complete in one course. The important thing is that you are making progress.", "action_item": "Decide if a second course would benefit your continued recovery."},
    {"day": 39, "phase": "Continued Recovery", "title": "Prevention Going Forward", "content": "The best injury is the one that never happens. Going forward: Warm up properly before activity, Progress training gradually, Address muscle imbalances, Listen to early warning signs, and Maintain good nutrition and sleep.\n\nYour body has shown you where it is vulnerable. Respect those signals and take care of that area going forward.", "action_item": "Create a prevention plan for your injury-prone area."},
    {"day": 40, "phase": "Continued Recovery", "title": "Final Injections Approaching", "content": "Two days of injections remaining. Make them count. Continue your BPC-157 near the injury site, continue your final TB-500 dose if scheduled.\n\nThink about how different this routine will feel when you are done. No more twice-daily injections. No more reconstituting vials. Just the results of your commitment.", "action_item": "Complete todays injections with full attention and intention."},
    {"day": 41, "phase": "Continued Recovery", "title": "Second to Last Day", "content": "One more day after today. Your injury recovery course is nearly complete.\n\nReflect on: How you felt on Day 0 vs. now, What you learned about your body, What you would do differently next time, and Whether this protocol worked for you.\n\nThese reflections help you make better decisions in the future.", "action_item": "Complete penultimate day of injections. Prepare for course completion."},
    {"day": 42, "phase": "Continued Recovery", "title": "Course Complete!", "content": "Congratulations! You have completed the 42-day Injury Recovery Course.\n\nYou have given your body 6 weeks of consistent healing support with aggressive loading followed by maintenance. The tissue repair you have stimulated will continue even now that the course is over.\n\nNext steps: Take a 4-week break if running another course, Continue gentle activity progression, Maintain good nutrition and sleep, Monitor your injury and note continued improvement.\n\nThank you for trusting this protocol. Your commitment to your health is admirable. Whether you return for another course or move forward healed, you have done the work.", "action_item": "Celebrate your completion and document your final results."}
  ]'::jsonb
WHERE goal = 'recovery';