
-- Update fat_loss and muscle/recovery courses with full 56-day content
-- These use explicit JSON which works

UPDATE course_templates 
SET lessons = '[
  {"day": 0, "phase": "Preparation", "title": "Welcome to Your Peptide Journey", "content": "Congratulations on taking this step. Over the next 56 days, you will transform your relationship with food and your body using semaglutide.", "action_item": "Read through the My Plan section"},
  {"day": 1, "phase": "Preparation", "title": "Understanding Semaglutide", "content": "Semaglutide works by mimicking GLP-1, a hormone your body produces naturally after eating. It signals fullness and reduces food noise.", "action_item": "Review the dosing schedule in My Plan"},
  {"day": 2, "phase": "Preparation", "title": "Supplies Checklist", "content": "Verify you have: Semaglutide vial, Bacteriostatic water, Insulin syringes, Alcohol swabs, Sharps container.", "action_item": "Check off each supply item"},
  {"day": 3, "phase": "Preparation", "title": "Reconstitution Prep", "content": "Tomorrow you will reconstitute your peptide. Review the reconstitution guide in My Plan.", "action_item": "Review the reconstitution guide"},
  {"day": 4, "phase": "Getting Started", "title": "Reconstitution Day", "content": "Today you prepare your peptide. Add 2ml BAC water slowly down the vial wall. Never shake - gentle swirl only.", "action_item": "Complete reconstitution"},
  {"day": 5, "phase": "Getting Started", "title": "Your First Injection", "content": "This is the moment. Draw 10 units (0.25mg), clean abdomen with alcohol, pinch skin, insert at 45 degrees, inject slowly.", "action_item": "Complete your first injection"},
  {"day": 6, "phase": "Getting Started", "title": "The Day After", "content": "Mild nausea and reduced appetite are normal. Stay hydrated and eat smaller portions.", "action_item": "Note how you feel"},
  {"day": 7, "phase": "Getting Started", "title": "Week 1 Complete", "content": "You have completed your first week. Set a reminder for your weekly injection day.", "action_item": "Set weekly injection reminder"},
  {"day": 8, "phase": "Building Routine", "title": "Managing Side Effects", "content": "Nausea usually fades by week 2-3. Eat slowly, avoid greasy foods, stay hydrated.", "action_item": "Track any side effects"},
  {"day": 9, "phase": "Building Routine", "title": "Nutrition Focus", "content": "Prioritize protein (100g+ daily) to preserve muscle during weight loss.", "action_item": "Plan protein-focused meals"},
  {"day": 10, "phase": "Building Routine", "title": "Second Injection", "content": "Complete your second injection at a rotated site. Same dose: 10 units (0.25mg).", "action_item": "Complete second injection"},
  {"day": 11, "phase": "Building Routine", "title": "Tracking Progress", "content": "Weekly weigh-ins are better than daily. Notice non-scale victories too.", "action_item": "Start weekly weigh-in routine"},
  {"day": 12, "phase": "Building Routine", "title": "Food Noise Quieting", "content": "Many notice reduced food thoughts around this time. This is the peptide working.", "action_item": "Reflect on food relationship changes"},
  {"day": 13, "phase": "Building Routine", "title": "Exercise Tips", "content": "Strength training 2-3x weekly preserves muscle. Listen to your body.", "action_item": "Plan strength training sessions"},
  {"day": 14, "phase": "Building Routine", "title": "Two Weeks Complete", "content": "Major milestone! Next week you increase to 0.5mg (20 units).", "action_item": "Prepare for dose increase"},
  {"day": 15, "phase": "Optimization", "title": "Increasing to 0.5mg", "content": "Draw 20 units today. Effects often increase noticeably at this dose.", "action_item": "Complete 0.5mg injection"},
  {"day": 16, "phase": "Optimization", "title": "Adjusting to Higher Dose", "content": "Stronger appetite suppression is normal. Still eat regular meals with protein focus.", "action_item": "Maintain regular eating schedule"},
  {"day": 17, "phase": "Optimization", "title": "Finding Your Sweet Spot", "content": "Some do best at 0.5mg, others need 1.0mg. Listen to your body.", "action_item": "Assess how you feel at this dose"},
  {"day": 18, "phase": "Optimization", "title": "Protein Priority", "content": "Target 100-150g protein daily. Eat protein first at each meal.", "action_item": "Calculate your protein intake"},
  {"day": 19, "phase": "Optimization", "title": "Results Showing", "content": "Around week 3, most see tangible results. Clothes fitting differently.", "action_item": "Take progress photos"},
  {"day": 20, "phase": "Optimization", "title": "Social Eating", "content": "Order smaller portions. Focus on conversation, not food.", "action_item": "Plan for social situations"},
  {"day": 21, "phase": "Optimization", "title": "Week 3 Complete", "content": "Three weeks in. You are past the adjustment phase.", "action_item": "Check in with AI Coach"},
  {"day": 22, "phase": "Optimization", "title": "Mindful Eating", "content": "Eat without distractions. Stop at 80% full.", "action_item": "Practice mindful eating"},
  {"day": 23, "phase": "Optimization", "title": "Sleep and Recovery", "content": "Quality sleep enhances results. Aim for 7-8 hours.", "action_item": "Track your sleep"},
  {"day": 24, "phase": "Optimization", "title": "Fourth Injection", "content": "Week 4 injection. Rotate to a new site.", "action_item": "Complete fourth injection"},
  {"day": 25, "phase": "Optimization", "title": "Handling Plateaus", "content": "Weight loss is not linear. Trust the process.", "action_item": "Take body measurements"},
  {"day": 26, "phase": "Optimization", "title": "Non-Scale Victories", "content": "Track energy, sleep, mood, clothes fit - not just weight.", "action_item": "Write down 3 non-scale victories"},
  {"day": 27, "phase": "Optimization", "title": "Building Habits", "content": "The goal is lasting change. Build sustainable habits now.", "action_item": "Identify one habit to solidify"},
  {"day": 28, "phase": "Optimization", "title": "One Month Complete!", "content": "Major milestone! Consider if you want to increase to 1.0mg.", "action_item": "Celebrate this milestone"},
  {"day": 29, "phase": "Mastery", "title": "The 1.0mg Decision", "content": "Stay at 0.5mg if working well, or increase to 1.0mg for more effect.", "action_item": "Decide your dose"},
  {"day": 30, "phase": "Mastery", "title": "Adjusting to Full Dose", "content": "If increasing, draw 40 units. Monitor for side effects.", "action_item": "Complete week 5 injection"},
  {"day": 31, "phase": "Mastery", "title": "Refining Your Approach", "content": "You know what works for you now. Personalize your approach.", "action_item": "Double down on what works"},
  {"day": 32, "phase": "Mastery", "title": "Energy Optimization", "content": "Consistent meals, protein, hydration, and sleep optimize energy.", "action_item": "Rate your energy level"},
  {"day": 33, "phase": "Mastery", "title": "Strength Training", "content": "2-3 sessions per week preserves muscle during weight loss.", "action_item": "Complete a strength session"},
  {"day": 34, "phase": "Mastery", "title": "Halfway Reflection", "content": "You are approaching the halfway point. Reflect on changes.", "action_item": "Compare today to Day 1"},
  {"day": 35, "phase": "Mastery", "title": "Week 5 Complete", "content": "Five weeks done. Solidify your routines.", "action_item": "Set a goal for month 2"},
  {"day": 36, "phase": "Mastery", "title": "Intuitive Eating", "content": "You are learning what real hunger and fullness feel like.", "action_item": "Notice hunger and fullness cues"},
  {"day": 37, "phase": "Mastery", "title": "Handling Cravings", "content": "Wait 15 minutes, have water, ask if you are truly hungry.", "action_item": "Identify your craving triggers"},
  {"day": 38, "phase": "Mastery", "title": "Week 6 Injection", "content": "More than halfway through. Progress check.", "action_item": "Complete sixth injection"},
  {"day": 39, "phase": "Mastery", "title": "Planning Maintenance", "content": "Think about what comes after the course.", "action_item": "Discuss post-course plan with AI Coach"},
  {"day": 40, "phase": "Mastery", "title": "Your Story", "content": "Document your transformation journey.", "action_item": "Write about your journey"},
  {"day": 41, "phase": "Mastery", "title": "Fine-Tuning Nutrition", "content": "Optimize your eating based on what you have learned.", "action_item": "Adjust nutrition based on learnings"},
  {"day": 42, "phase": "Mastery", "title": "Six Weeks Complete", "content": "You have passed the halfway point. Two weeks to go.", "action_item": "Set goals for final two weeks"},
  {"day": 43, "phase": "Mastery", "title": "Final Phase Begins", "content": "Welcome to week 7. Maintain consistency.", "action_item": "Commit to strong finish"},
  {"day": 44, "phase": "Mastery", "title": "Seventh Injection", "content": "Second to last injection. You have come so far.", "action_item": "Complete seventh injection"},
  {"day": 45, "phase": "Mastery", "title": "Sustaining Results", "content": "Habits over willpower for long-term success.", "action_item": "Identify 3 habits to maintain"},
  {"day": 46, "phase": "Mastery", "title": "Support System", "content": "Success is easier with support. Share with trusted people.", "action_item": "Share progress with someone"},
  {"day": 47, "phase": "Mastery", "title": "Handling Setbacks", "content": "Setbacks happen. Acknowledge, learn, move forward.", "action_item": "Plan for future setbacks"},
  {"day": 48, "phase": "Mastery", "title": "Mental Changes", "content": "Transformation is more than physical. Honor all of it.", "action_item": "Reflect on mental changes"},
  {"day": 49, "phase": "Mastery", "title": "Week 7 Complete", "content": "One week to go. Plan your celebration.", "action_item": "Plan completion celebration"},
  {"day": 50, "phase": "Mastery", "title": "Final Week", "content": "This is it. Finish as strong as you started.", "action_item": "Write your post-course plan"},
  {"day": 51, "phase": "Mastery", "title": "Final Injection", "content": "Your eighth and final injection. Congratulations.", "action_item": "Complete final injection"},
  {"day": 52, "phase": "Mastery", "title": "Day After Final", "content": "Effects continue for 2-3 weeks. Rely on your habits.", "action_item": "Notice how you feel"},
  {"day": 53, "phase": "Mastery", "title": "Maintaining Momentum", "content": "Keep your daily practices. They are your foundation.", "action_item": "Schedule weekly check-ins"},
  {"day": 54, "phase": "Mastery", "title": "Your Toolkit", "content": "You have skills, knowledge, and experience now.", "action_item": "List top 5 takeaways"},
  {"day": 55, "phase": "Mastery", "title": "Final Preparation", "content": "Tomorrow is day 56. Take final photos and measurements.", "action_item": "Complete final documentation"},
  {"day": 56, "phase": "Mastery", "title": "Course Complete!", "content": "Congratulations! You completed 56 days. You are transformed.", "action_item": "Celebrate your success!"}
]'::jsonb,
duration_days = 56
WHERE goal = 'fat_loss';
